# Created by: Daniel Morante <daniel@morante.net>
# $FreeBSD$

PORTNAME=	secp256k1
PORTVERSION=	0.0.0.1
PORTREVSION=	1
CATEGORIES=	security

MAINTAINER=	daniel@morante.net
COMMENT=	Optimized C library for EC operations on curve secp256k1

LICENSE=	MIT

USE_GITHUB=	yes
GH_ACCOUNT=	bitcoin-core
GH_COMMIT=	729badf
GH_TAGNAME=	729badf

USES=		autoreconf gmake libtool pkgconfig
USE_LDCONFIG=	yes
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
